INSTRUCTION_REFERENCE_ROWS = [
    {
        "Instruction": "LD",
        "Meaning": "Load",
        "LadderExample": "|--[ X0 ]--",
        "Description": "Starts a condition using a normally open contact.",
    },
    {
        "Instruction": "AND",
        "Meaning": "And",
        "LadderExample": "|--[ X0 ]--[ X1 ]--",
        "Description": "Adds a serial condition. All serial conditions must be true.",
    },
    {
        "Instruction": "OR",
        "Meaning": "Or",
        "LadderExample": "Parallel branch",
        "Description": "Adds a parallel condition. Any branch can make the condition true.",
    },
    {
        "Instruction": "ANI",
        "Meaning": "And Not",
        "LadderExample": "|--[ X0 ]--[/ X1 ]--",
        "Description": "Adds a serial normally closed condition.",
    },
    {
        "Instruction": "OUT",
        "Meaning": "Output",
        "LadderExample": "|--[ X0 ]--( Y0 )--",
        "Description": "Writes the condition result to an output coil or internal bit.",
    },
    {
        "Instruction": "SET",
        "Meaning": "Set",
        "LadderExample": "|--[ X0 ]--( SET M0 )--",
        "Description": "Turns a bit on and keeps it on until it is reset.",
    },
    {
        "Instruction": "RST",
        "Meaning": "Reset",
        "LadderExample": "|--[ X1 ]--( RST M0 )--",
        "Description": "Turns a set bit off.",
    },
    {
        "Instruction": "MOV",
        "Meaning": "Move",
        "LadderExample": "MOV D0 D10",
        "Description": "Copies a value from a source device to a destination device.",
    },
    {
        "Instruction": "DMOV",
        "Meaning": "Double Move",
        "LadderExample": "DMOV SD1880 D2000",
        "Description": "Copies a 32-bit value, usually using two consecutive words.",
    },
    {
        "Instruction": "INC",
        "Meaning": "Increment",
        "LadderExample": "INC D0",
        "Description": "Increases the target device value by one.",
    },
]


CHECK_REFERENCE_ROWS = [
    {
        "Type": "MISSING_DEVICE_COMMENT",
        "Level": "WARN",
        "Category": "Documentation",
        "Meaning": "An X/Y device is used in ladder CSV, but no device comment is registered.",
        "ReviewPoint": "The signal name or field meaning is unclear from the I/O list.",
        "SuggestedAction": "Check the GX Works2 device comment table or electrical drawing, then add the missing comment.",
    },
    {
        "Type": "MISSING_LOGIC_NOTE",
        "Level": "INFO",
        "Category": "LogicContext",
        "Meaning": "No nearby ladder note was found for the X/Y device.",
        "ReviewPoint": "This is not always a defect, but the logic context may be harder to understand.",
        "SuggestedAction": "Use DeviceComment as the main source and review the ladder around the listed step if needed.",
    },
    {
        "Type": "MULTIPLE_USED_FILES",
        "Level": "WARN",
        "Category": "Usage",
        "Meaning": "The same X/Y device is referenced in multiple ladder CSV files.",
        "ReviewPoint": "A change to this I/O may affect more than one program section.",
        "SuggestedAction": "Open the listed files and confirm whether the shared usage is intentional.",
    },
    {
        "Type": "MULTIPLE_LOGIC_NOTES",
        "Level": "WARN",
        "Category": "LogicContext",
        "Meaning": "Multiple ladder notes were linked to the same X/Y device.",
        "ReviewPoint": "A logic note may describe an operation, not the device name itself.",
        "SuggestedAction": "Compare the notes and use them as context instead of blindly copying them as signal names.",
    },
    {
        "Type": "COMMENTED_BUT_NOT_USED",
        "Level": "WARN",
        "Category": "Documentation",
        "Meaning": "A device comment exists, but the X/Y device was not found in ladder CSV.",
        "ReviewPoint": "The comment may be obsolete, reserved, or the ladder export may be incomplete.",
        "SuggestedAction": "Confirm whether the address is spare, deleted, or used in a program that was not exported.",
    },
    {
        "Type": "SPARE_OR_UNUSED_DEVICE",
        "Level": "INFO",
        "Category": "Documentation",
        "Meaning": "The X/Y device is commented as spare or unused and was not found in ladder CSV.",
        "ReviewPoint": "This is usually acceptable, but it is useful to keep visible in the report.",
        "SuggestedAction": "Treat as reference information unless the project expects every spare address to be excluded.",
    },
]


DEVICE_TYPE_REFERENCE_ROWS = [
    {
        "DeviceType": "X",
        "UsageCategory": "PhysicalIO",
        "Meaning": "Input",
        "Example": "X0",
        "Description": "Physical input such as a sensor, push button, or switch.",
    },
    {
        "DeviceType": "Y",
        "UsageCategory": "PhysicalIO",
        "Meaning": "Output",
        "Example": "Y0",
        "Description": "Physical output such as a lamp, relay, solenoid, or actuator signal.",
    },
    {
        "DeviceType": "M",
        "UsageCategory": "InternalDevice",
        "Meaning": "Internal relay",
        "Example": "M100",
        "Description": "Internal bit used inside the PLC program.",
    },
    {
        "DeviceType": "L",
        "UsageCategory": "InternalDevice",
        "Meaning": "Latch relay",
        "Example": "L100",
        "Description": "Internal bit that can retain its state depending on PLC settings.",
    },
    {
        "DeviceType": "B",
        "UsageCategory": "InternalDevice",
        "Meaning": "Link relay",
        "Example": "B10",
        "Description": "Bit device often used for link or network-related data areas.",
    },
    {
        "DeviceType": "W",
        "UsageCategory": "InternalDevice",
        "Meaning": "Link register",
        "Example": "W10",
        "Description": "Word device often used for link or network-related data areas.",
    },
    {
        "DeviceType": "R",
        "UsageCategory": "InternalDevice",
        "Meaning": "File register",
        "Example": "R100",
        "Description": "Word register used as an extended data storage area.",
    },
    {
        "DeviceType": "ZR",
        "UsageCategory": "InternalDevice",
        "Meaning": "File register",
        "Example": "ZR1000",
        "Description": "Extended file register used as a large data storage area.",
    },
    {
        "DeviceType": "SM",
        "UsageCategory": "SpecialDevice",
        "Meaning": "Special relay",
        "Example": "SM402",
        "Description": "System bit provided by the PLC CPU or special function area.",
    },
    {
        "DeviceType": "D",
        "UsageCategory": "InternalDevice",
        "Meaning": "Data register",
        "Example": "D2000",
        "Description": "Word register used to store numeric values.",
    },
    {
        "DeviceType": "SD",
        "UsageCategory": "SpecialDevice",
        "Meaning": "Special data register",
        "Example": "SD1880",
        "Description": "System data register provided by the PLC CPU or special function area.",
    },
    {
        "DeviceType": "K",
        "UsageCategory": "Constant",
        "Meaning": "Decimal constant",
        "Example": "K1000",
        "Description": "Fixed decimal value used as an instruction parameter.",
    },
    {
        "DeviceType": "H",
        "UsageCategory": "Constant",
        "Meaning": "Hex constant",
        "Example": "H1",
        "Description": "Fixed hexadecimal value used as an instruction parameter.",
    },
    {
        "DeviceType": "T",
        "UsageCategory": "TimerCounter",
        "Meaning": "Timer",
        "Example": "T0",
        "Description": "Timer device used for time-based control.",
    },
    {
        "DeviceType": "C",
        "UsageCategory": "TimerCounter",
        "Meaning": "Counter",
        "Example": "C0",
        "Description": "Counter device used for count-based control.",
    },
]
